baseurl = "https://hoangtrungkien210895.github.io/"
languageCode = 'en-us'
metaDataFormat = "yaml"
title = "Hoang Kien"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Mình là Kiên"
      introSubtitle = "Ý tưởng của mình khi tạo blog này là muốn gửi kiến thức IT theo 1 cách đơn giản cho những thứ tưởng chừng là “phức tạp”"
      introPhoto = "/kien.jpeg"
      logo = "/home2.jpeg"
    [[languages.en.menu.main]]
        name = "Blog của Kiên"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About's Kiên"
        url = "page/about/"
        weight = 2
        
  [languages.fr]
    contentDir = "content/fr" #French
    weight = 1
    languageName = "English"
    [languages.fr.params]
      introTitle = "Mình là Kiên"
      introSubtitle = "Ý tưởng của mình khi tạo blog này là muốn gửi kiến thức IT theo 1 cách đơn giản cho những thứ tưởng chừng là “phức tạp”"
      introPhoto = "/kien.jpeg"
      logo = "/home2.jpeg"
    [[languages.fr.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.fr.menu.main]]
        name = "À propos"
        url = "page/about/"
        weight = 2

    [[languages.fr.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = false

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Katheryn Fox · All rights reserved"
  favicon = "/favicon.jpeg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "Theo dõi group trên facebook của mình"
  facebook = "https://www.facebook.com/groups/1058223478229630"
 

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
